// MonaIconRegistry.swift
//
// P05-T006 — Implement theme, token, color, icon, and Codicon registries.
//
// GENERATED FILE — do not edit by hand. Transcribed verbatim from the F1-R3
// scope manifest (monaco-editor@0.56.0 builtin colors/icons/themes/Codicon
// glyphs). Regenerate by re-running the P05-T006 transcription against the
// manifest at:
//   docs/contracts/monaco-editor-0.56.0/g6-r/artifacts/parent/g5-r/artifacts/monaco-0.56.0-f1r3-scope-manifest.json
//
// MonaCode is a Foundation-only target: `import Foundation` is the sole import.
import Foundation

// MARK: - Icon model

/// A builtin product-icon definition transcribed verbatim from the F1-R3
/// manifest (`registries.icons`).
public struct MonaIconDefinition: Sendable, Equatable {
    public let id: String
    /// The Codicon codepoint as a lowercase hex string without the leading
    /// backslash (e.g. "eb99"). `nil` for deprecated alias icons whose
    /// `defaults` was `{id: <target>}` rather than `{fontCharacter: ...}`.
    public let codepointHex: String?
    /// For the 34 deprecated alias icons, the icon id this alias resolves to.
    public let deprecatedAliasOf: String?
    public init(id: String, codepointHex: String?, deprecatedAliasOf: String?) {
        self.id = id
        self.codepointHex = codepointHex
        self.deprecatedAliasOf = deprecatedAliasOf
    }

    /// `true` when this entry is a deprecated alias of another icon.
    public var isAlias: Bool { deprecatedAliasOf != nil }
}

/// Icon modifiers applied at the use site (the manifest does not bind modifiers
/// to individual icons; they decorate a resolved icon, matching Monaco's
/// `IconModifier`). Rendered by the native layer.
public enum MonaIconModifier: String, Sendable, CaseIterable {
    case spin
    case alignLeft = "align-left"
    case alignRight = "align-right"
    case alignCenter = "align-center"
}

// MARK: - Icon registry

/// The 776 builtin product-icon definitions ported verbatim from
/// monaco-editor@0.56.0 (F1-R3 manifest `registries.icons`), plus alias
/// resolution.
public enum MonaIconRegistry {

    /// All 776 builtin product-icon definitions in source-ordinal order.
    public static let icons: [MonaIconDefinition] = [
        MonaIconDefinition(id: "account", codepointHex: "eb99", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "activate-breakpoints", codepointHex: "ea97", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "add", codepointHex: "ea60", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "add-compact", codepointHex: "ec9f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "add-small", codepointHex: "ec7b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "agent", codepointHex: "ec67", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "agent-compact", codepointHex: "ecc0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "alert", codepointHex: "ea6c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "archive", codepointHex: "ea98", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "array", codepointHex: "ea8a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "arrow-both", codepointHex: "ea99", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "arrow-circle-down", codepointHex: "ebfc", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "arrow-circle-left", codepointHex: "ebfd", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "arrow-circle-right", codepointHex: "ebfe", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "arrow-circle-up", codepointHex: "ebff", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "arrow-down", codepointHex: "ea9a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "arrow-left", codepointHex: "ea9b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "arrow-right", codepointHex: "ea9c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "arrow-small-down", codepointHex: "ea9d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "arrow-small-left", codepointHex: "ea9e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "arrow-small-right", codepointHex: "ea9f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "arrow-small-up", codepointHex: "eaa0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "arrow-swap", codepointHex: "ebcb", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "arrow-up", codepointHex: "eaa1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "ask", codepointHex: "ec80", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "ask-compact", codepointHex: "ecc1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "attach", codepointHex: "ec34", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "attach-compact", codepointHex: "eca0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "azure", codepointHex: "ebd8", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "azure-devops", codepointHex: "ebe8", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "beaker", codepointHex: "ea79", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "beaker-compact", codepointHex: "eca1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "beaker-stop", codepointHex: "ebe1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "bell", codepointHex: "eaa2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "bell-dot", codepointHex: "eb9a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "bell-slash", codepointHex: "ec08", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "bell-slash-dot", codepointHex: "ec09", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "blank", codepointHex: "ec03", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "bold", codepointHex: "eaa3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "book", codepointHex: "eaa4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "bookmark", codepointHex: "eaa5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "bracket", codepointHex: "eb0f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "bracket-dot", codepointHex: "ebe5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "bracket-error", codepointHex: "ebe6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "briefcase", codepointHex: "eaac", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "broadcast", codepointHex: "eaad", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "browser", codepointHex: "eaae", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "bug", codepointHex: "eaaf", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "build", codepointHex: "ec5a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "calendar", codepointHex: "eab0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "call-incoming", codepointHex: "eb92", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "call-outgoing", codepointHex: "eb93", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "case-sensitive", codepointHex: "eab1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chat-export", codepointHex: "ec87", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chat-import", codepointHex: "ec86", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chat-sparkle", codepointHex: "ec4f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chat-sparkle-error", codepointHex: "ec56", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chat-sparkle-warning", codepointHex: "ec55", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "check", codepointHex: "eab2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "check-all", codepointHex: "ebb1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "check-compact", codepointHex: "eca2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "checklist", codepointHex: "eab3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "checklist-compact", codepointHex: "eca3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chevron-down", codepointHex: "eab4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chevron-down-compact", codepointHex: "eca4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chevron-left", codepointHex: "eab5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chevron-left-compact", codepointHex: "eca5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chevron-right", codepointHex: "eab6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chevron-right-compact", codepointHex: "eca6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chevron-up", codepointHex: "eab7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chevron-up-compact", codepointHex: "eca7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chip", codepointHex: "ec19", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chrome-close", codepointHex: "eab8", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chrome-maximize", codepointHex: "eab9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chrome-minimize", codepointHex: "eaba", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "chrome-restore", codepointHex: "eabb", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "circle", codepointHex: "eabc", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "circle-filled", codepointHex: "ea71", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "circle-filled-compact", codepointHex: "eca8", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "circle-large", codepointHex: "ebb5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "circle-large-filled", codepointHex: "ebb4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "circle-large-outline", codepointHex: "ebb5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "circle-outline", codepointHex: "eabc", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "circle-slash", codepointHex: "eabd", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "circle-slash-compact", codepointHex: "ec89", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "circle-small", codepointHex: "ec07", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "circle-small-filled", codepointHex: "eb8a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "circle-small-filled-compact", codepointHex: "eca9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "circuit-board", codepointHex: "eabe", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "claude", codepointHex: "ec82", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "clear-all", codepointHex: "eabf", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "clippy", codepointHex: "eac0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "clock", codepointHex: "ea82", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "clockface", codepointHex: "ec75", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "clone", codepointHex: "ea78", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "close", codepointHex: "ea76", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "close-all", codepointHex: "eac1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "close-compact", codepointHex: "ecaa", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "close-dirty", codepointHex: "ea71", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "cloud", codepointHex: "ebaa", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "cloud-compact", codepointHex: "ecbf", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "cloud-download", codepointHex: "eac2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "cloud-small", codepointHex: "ec7a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "cloud-upload", codepointHex: "eac3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "code", codepointHex: "eac4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "code-oss", codepointHex: "ec2b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "code-review", codepointHex: "ec37", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "coffee", codepointHex: "ec15", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "collapse-all", codepointHex: "eac5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "collapse-all-compact", codepointHex: "ecab", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "collection", codepointHex: "ec57", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "collection-small", codepointHex: "ec78", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "color-mode", codepointHex: "eac6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "combine", codepointHex: "ebb6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "comment", codepointHex: "ea6b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "comment-add", codepointHex: "ea6b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "comment-compact", codepointHex: "ecac", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "comment-discussion", codepointHex: "eac7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "comment-discussion-quote", codepointHex: "ec5b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "comment-discussion-sparkle", codepointHex: "ec54", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "comment-draft", codepointHex: "ec0e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "comment-unresolved", codepointHex: "ec0a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "comment-unresolved-compact", codepointHex: "ecad", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "compare-changes", codepointHex: "eafd", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "compass", codepointHex: "ebd5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "compass-active", codepointHex: "ebd7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "compass-dot", codepointHex: "ebd6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "console", codepointHex: "ea85", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "copilot", codepointHex: "ec1e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "copilot-blocked", codepointHex: "ec3d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "copilot-compact", codepointHex: "ec8a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "copilot-error", codepointHex: "ec4d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "copilot-in-progress", codepointHex: "ec4c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "copilot-large", codepointHex: "ec3a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "copilot-not-connected", codepointHex: "ec3e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "copilot-snooze", codepointHex: "ec52", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "copilot-success", codepointHex: "ec4e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "copilot-unavailable", codepointHex: "ec42", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "copilot-warning", codepointHex: "ec38", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "copilot-warning-large", codepointHex: "ec3b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "copy", codepointHex: "ebcc", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "coverage", codepointHex: "ec2e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "credit-card", codepointHex: "eac9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "cursor", codepointHex: "ec5c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "dash", codepointHex: "eacc", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "dashboard", codepointHex: "eacd", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "database", codepointHex: "eace", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug", codepointHex: "ead8", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-all", codepointHex: "ebdc", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-alt", codepointHex: "eb91", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-alt-small", codepointHex: "eba8", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint", codepointHex: "ea71", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-conditional", codepointHex: "eaa7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-conditional-disabled", codepointHex: "eaa7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-conditional-unverified", codepointHex: "eaa6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-data", codepointHex: "eaa9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-data-disabled", codepointHex: "eaa9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-data-unverified", codepointHex: "eaa8", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-disabled", codepointHex: "ea71", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-function", codepointHex: "eb88", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-function-disabled", codepointHex: "eb88", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-function-unverified", codepointHex: "eb87", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-log", codepointHex: "eaab", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-log-disabled", codepointHex: "eaab", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-log-unverified", codepointHex: "eaaa", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-pending", codepointHex: "ebd9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-unsupported", codepointHex: "eb8c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-breakpoint-unverified", codepointHex: "eabc", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-connected", codepointHex: "ec63", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-connected-compact", codepointHex: "ecae", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-console", codepointHex: "eb9b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-continue", codepointHex: "eacf", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-continue-small", codepointHex: "ebe0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-coverage", codepointHex: "ebdd", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-disconnect", codepointHex: "ead0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-disconnect-compact", codepointHex: "ecaf", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-hint", codepointHex: "ea71", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-line-by-line", codepointHex: "ebd0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-pause", codepointHex: "ead1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-rerun", codepointHex: "ebc0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-restart", codepointHex: "ead2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-restart-frame", codepointHex: "eb90", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-reverse-continue", codepointHex: "eb8e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-stackframe", codepointHex: "eb8b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-stackframe-active", codepointHex: "eb89", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-stackframe-dot", codepointHex: "eb8a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-stackframe-focused", codepointHex: "eb8b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-start", codepointHex: "ead3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-step-back", codepointHex: "eb8f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-step-into", codepointHex: "ead4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-step-out", codepointHex: "ead5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-step-over", codepointHex: "ead6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "debug-stop", codepointHex: "ead7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "desktop-download", codepointHex: "ea78", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "developer-tools", codepointHex: "ecbe", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "device-camera", codepointHex: "eada", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "device-camera-video", codepointHex: "ead9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "device-desktop", codepointHex: "ea7a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "device-mobile", codepointHex: "eadb", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "dialog-close", codepointHex: "ea76", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "dialog-error", codepointHex: "ea87", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "dialog-info", codepointHex: "ea74", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "dialog-warning", codepointHex: "ea6c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "diff", codepointHex: "eae1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "diff-added", codepointHex: "eadc", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "diff-ignored", codepointHex: "eadd", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "diff-insert", codepointHex: nil, deprecatedAliasOf: "add"),
        MonaIconDefinition(id: "diff-modified", codepointHex: "eade", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "diff-multiple", codepointHex: "ec23", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "diff-remove", codepointHex: nil, deprecatedAliasOf: "remove"),
        MonaIconDefinition(id: "diff-removed", codepointHex: "eadf", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "diff-renamed", codepointHex: "eae0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "diff-review-close", codepointHex: nil, deprecatedAliasOf: "close"),
        MonaIconDefinition(id: "diff-review-insert", codepointHex: nil, deprecatedAliasOf: "add"),
        MonaIconDefinition(id: "diff-review-remove", codepointHex: nil, deprecatedAliasOf: "remove"),
        MonaIconDefinition(id: "diff-sidebyside", codepointHex: "eae1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "diff-single", codepointHex: "ec22", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "discard", codepointHex: "eae2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "download", codepointHex: "ec74", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "drop-down-button", codepointHex: "eab4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "edit", codepointHex: "ea73", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "edit-code", codepointHex: "ec68", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "edit-compact", codepointHex: "ecb0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "edit-session", codepointHex: "ec36", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "edit-sparkle", codepointHex: "ec51", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "editor-layout", codepointHex: "eae3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "ellipsis", codepointHex: "ea7c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "empty-window", codepointHex: "eae4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "eraser", codepointHex: "ec5d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "error", codepointHex: "ea87", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "error-compact", codepointHex: "ec98", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "error-small", codepointHex: "ebfb", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "exclude", codepointHex: "eae5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "expand-all", codepointHex: "eb95", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "export", codepointHex: "ebac", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "extensions", codepointHex: "eae6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "extensions-large", codepointHex: "ec48", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "extensions-warning-message", codepointHex: nil, deprecatedAliasOf: "warning"),
        MonaIconDefinition(id: "eye", codepointHex: "ea70", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "eye-closed", codepointHex: "eae7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "eye-unwatch", codepointHex: "ea70", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "eye-watch", codepointHex: "ea70", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "feedback", codepointHex: "eb96", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "file", codepointHex: "ea7b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "file-add", codepointHex: "ea7f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "file-binary", codepointHex: "eae8", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "file-code", codepointHex: "eae9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "file-directory", codepointHex: "ea83", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "file-directory-create", codepointHex: "ea80", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "file-media", codepointHex: "eaea", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "file-media-compact", codepointHex: "ecb1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "file-pdf", codepointHex: "eaeb", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "file-submodule", codepointHex: "eaec", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "file-symlink-directory", codepointHex: "eaed", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "file-symlink-file", codepointHex: "eaee", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "file-text", codepointHex: "ec5e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "file-zip", codepointHex: "eaef", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "files", codepointHex: "eaf0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "filter", codepointHex: "eaf1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "filter-filled", codepointHex: "ebce", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "find-collapsed", codepointHex: nil, deprecatedAliasOf: "chevron-right"),
        MonaIconDefinition(id: "find-expanded", codepointHex: nil, deprecatedAliasOf: "chevron-down"),
        MonaIconDefinition(id: "find-next-match", codepointHex: nil, deprecatedAliasOf: "arrow-down"),
        MonaIconDefinition(id: "find-previous-match", codepointHex: nil, deprecatedAliasOf: "arrow-up"),
        MonaIconDefinition(id: "find-replace", codepointHex: nil, deprecatedAliasOf: "replace"),
        MonaIconDefinition(id: "find-replace-all", codepointHex: nil, deprecatedAliasOf: "replace-all"),
        MonaIconDefinition(id: "find-selection", codepointHex: nil, deprecatedAliasOf: "selection"),
        MonaIconDefinition(id: "flag", codepointHex: "ec3f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "flame", codepointHex: "eaf2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "fold", codepointHex: "eaf5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "fold-down", codepointHex: "eaf3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "fold-horizontal", codepointHex: "ec05", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "fold-horizontal-filled", codepointHex: "ec06", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "fold-up", codepointHex: "eaf4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "fold-vertical", codepointHex: "ec30", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "fold-vertical-filled", codepointHex: "ec31", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "folder", codepointHex: "ea83", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "folder-active", codepointHex: "eaf6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "folder-compact", codepointHex: "ec8c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "folder-library", codepointHex: "ebdf", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "folder-opened", codepointHex: "eaf7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "folder-opened-compact", codepointHex: "ec8b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "folding-collapsed", codepointHex: nil, deprecatedAliasOf: "chevron-right"),
        MonaIconDefinition(id: "folding-expanded", codepointHex: nil, deprecatedAliasOf: "chevron-down"),
        MonaIconDefinition(id: "folding-manual-collapsed", codepointHex: nil, deprecatedAliasOf: "folding-collapsed"),
        MonaIconDefinition(id: "folding-manual-expanded", codepointHex: nil, deprecatedAliasOf: "folding-expanded"),
        MonaIconDefinition(id: "forward", codepointHex: "ec73", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "game", codepointHex: "ec17", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "gather", codepointHex: "ebb6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "gear", codepointHex: "eaf8", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "gear-compact", codepointHex: "ec8d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "gift", codepointHex: "eaf9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "gist", codepointHex: "eafb", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "gist-fork", codepointHex: "ea63", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "gist-new", codepointHex: "ea60", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "gist-private", codepointHex: "ea75", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "gist-secret", codepointHex: "eafa", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-branch", codepointHex: "ec6f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-branch-changes", codepointHex: "ec6c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-branch-compact", codepointHex: "ec8e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-branch-conflicts", codepointHex: "ec6e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-branch-create", codepointHex: "ec6f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-branch-delete", codepointHex: "ec6f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-branch-staged-changes", codepointHex: "ec6d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-commit", codepointHex: "eafc", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-compare", codepointHex: "eafd", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-fetch", codepointHex: "ec1d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-fork-private", codepointHex: "ea75", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-merge", codepointHex: "eafe", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-pull-request", codepointHex: "ea64", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-pull-request-abandoned", codepointHex: "ea64", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-pull-request-assignee", codepointHex: "eb99", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-pull-request-closed", codepointHex: "ebda", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-pull-request-comment", codepointHex: "ecc5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-pull-request-create", codepointHex: "ebbc", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-pull-request-done", codepointHex: "ec46", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-pull-request-draft", codepointHex: "ebdb", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-pull-request-error", codepointHex: "ecc6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-pull-request-go-to-changes", codepointHex: "ec0b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-pull-request-label", codepointHex: "ea66", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-pull-request-milestone", codepointHex: "eb20", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-pull-request-new-changes", codepointHex: "ec0c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-pull-request-reviewer", codepointHex: "eb96", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-stash", codepointHex: "ec26", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-stash-apply", codepointHex: "ec27", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "git-stash-pop", codepointHex: "ec28", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "github", codepointHex: "ea84", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "github-action", codepointHex: "eaff", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "github-alt", codepointHex: "eb00", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "github-inverted", codepointHex: "eba1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "github-project", codepointHex: "ec2f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "globe", codepointHex: "eb01", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "go-to-editing-session", codepointHex: "ec35", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "go-to-file", codepointHex: "ea94", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "go-to-search", codepointHex: "ec32", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "goto-next-location", codepointHex: nil, deprecatedAliasOf: "arrow-down"),
        MonaIconDefinition(id: "goto-previous-location", codepointHex: nil, deprecatedAliasOf: "arrow-up"),
        MonaIconDefinition(id: "grabber", codepointHex: "eb02", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "graph", codepointHex: "eb03", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "graph-left", codepointHex: "ebad", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "graph-line", codepointHex: "ebe2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "graph-scatter", codepointHex: "ebe3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "gripper", codepointHex: "eb04", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "group-by-ref-type", codepointHex: "eb97", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "gutter-lightbulb", codepointHex: nil, deprecatedAliasOf: "light-bulb"),
        MonaIconDefinition(id: "gutter-lightbulb-aifix-auto-fix", codepointHex: nil, deprecatedAliasOf: "lightbulb-sparkle-autofix"),
        MonaIconDefinition(id: "gutter-lightbulb-auto-fix", codepointHex: nil, deprecatedAliasOf: "lightbulb-autofix"),
        MonaIconDefinition(id: "gutter-lightbulb-sparkle", codepointHex: nil, deprecatedAliasOf: "lightbulb-sparkle"),
        MonaIconDefinition(id: "gutter-lightbulb-sparkle-filled", codepointHex: nil, deprecatedAliasOf: "sparkle-filled"),
        MonaIconDefinition(id: "heart", codepointHex: "eb05", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "heart-filled", codepointHex: "ec04", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "history", codepointHex: "ea82", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "home", codepointHex: "eb06", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "horizontal-rule", codepointHex: "eb07", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "hover-decrease-verbosity", codepointHex: nil, deprecatedAliasOf: "remove-small"),
        MonaIconDefinition(id: "hover-increase-verbosity", codepointHex: nil, deprecatedAliasOf: "add-small"),
        MonaIconDefinition(id: "hubot", codepointHex: "eb08", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "important", codepointHex: "ec9b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "important-compact", codepointHex: "ec9c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "inbox", codepointHex: "eb09", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "indent", codepointHex: "ebf9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "index-zero", codepointHex: "ec66", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "info", codepointHex: "ea74", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "inline-suggestion-hints-next", codepointHex: nil, deprecatedAliasOf: "chevron-right"),
        MonaIconDefinition(id: "inline-suggestion-hints-previous", codepointHex: nil, deprecatedAliasOf: "chevron-left"),
        MonaIconDefinition(id: "insert", codepointHex: "ec11", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "inspect", codepointHex: "ebd1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "issue-closed", codepointHex: "eba4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "issue-draft", codepointHex: "ebd9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "issue-opened", codepointHex: "ea74", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "issue-reopened", codepointHex: "eb0b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "issues", codepointHex: "eb0c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "italic", codepointHex: "eb0d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "jersey", codepointHex: "eb0e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "json", codepointHex: "eb0f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "kebab-horizontal", codepointHex: "ea7c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "kebab-vertical", codepointHex: "eb10", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "key", codepointHex: "eb11", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "keyboard", codepointHex: "ea65", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "keyboard-tab", codepointHex: "ec3c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "keyboard-tab-above", codepointHex: "ec44", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "keyboard-tab-below", codepointHex: "ec45", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "law", codepointHex: "eb12", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layers", codepointHex: "ebd2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layers-active", codepointHex: "ebd4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layers-dot", codepointHex: "ebd3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout", codepointHex: "ebeb", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-activitybar-left", codepointHex: "ebec", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-activitybar-right", codepointHex: "ebed", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-centered", codepointHex: "ebf7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-menubar", codepointHex: "ebf6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-panel", codepointHex: "ebf2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-panel-center", codepointHex: "ebef", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-panel-dock", codepointHex: "ec49", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-panel-justify", codepointHex: "ebf0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-panel-left", codepointHex: "ebee", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-panel-off", codepointHex: "ec01", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-panel-right", codepointHex: "ebf1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-sidebar-left", codepointHex: "ebf3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-sidebar-left-dock", codepointHex: "ec4a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-sidebar-left-off", codepointHex: "ec02", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-sidebar-right", codepointHex: "ebf4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-sidebar-right-dock", codepointHex: "ec4b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-sidebar-right-off", codepointHex: "ec00", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "layout-statusbar", codepointHex: "ebf5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "library", codepointHex: "eb9c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "library-compact", codepointHex: "ec8f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "light-bulb", codepointHex: "ea61", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "lightbulb", codepointHex: "ea61", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "lightbulb-autofix", codepointHex: "eb13", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "lightbulb-compact", codepointHex: "ecb3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "lightbulb-empty", codepointHex: "ec40", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "lightbulb-sparkle", codepointHex: "ec1f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "lightbulb-sparkle-autofix", codepointHex: "ec1f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "link", codepointHex: "eb15", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "link-external", codepointHex: "eb14", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "list-filter", codepointHex: "eb83", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "list-flat", codepointHex: "eb84", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "list-ordered", codepointHex: "eb16", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "list-selection", codepointHex: "eb85", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "list-tree", codepointHex: "eb86", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "list-unordered", codepointHex: "eb17", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "live-share", codepointHex: "eb18", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "loading", codepointHex: "eb19", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "loading-compact", codepointHex: "ecb4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "location", codepointHex: "eb1a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "lock", codepointHex: "ea75", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "lock-small", codepointHex: "ebe7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "log-in", codepointHex: "ea6f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "log-out", codepointHex: "ea6e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "logo-github", codepointHex: "ea84", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "magnet", codepointHex: "ebae", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "mail", codepointHex: "eb1c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "mail-read", codepointHex: "eb1b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "mail-reply", codepointHex: "ea7d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "map", codepointHex: "ec05", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "map-filled", codepointHex: "ec06", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "map-horizontal", codepointHex: "ec05", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "map-horizontal-filled", codepointHex: "ec06", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "map-vertical", codepointHex: "ec30", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "map-vertical-filled", codepointHex: "ec31", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "mark-github", codepointHex: "ea84", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "markdown", codepointHex: "eb1d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "marker-navigation-next", codepointHex: nil, deprecatedAliasOf: "arrow-down"),
        MonaIconDefinition(id: "marker-navigation-previous", codepointHex: nil, deprecatedAliasOf: "arrow-up"),
        MonaIconDefinition(id: "mcp", codepointHex: "ec47", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "megaphone", codepointHex: "eb1e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "mention", codepointHex: "eb1f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "menu", codepointHex: "eb94", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "menu-selection", codepointHex: "eab2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "menu-submenu", codepointHex: "eab6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "menubar-more", codepointHex: "ea7c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "merge", codepointHex: "ebab", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "merge-into", codepointHex: "ec6b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "mic", codepointHex: "ec12", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "mic-filled", codepointHex: "ec1c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "microscope", codepointHex: "ea79", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "milestone", codepointHex: "eb20", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "mirror", codepointHex: "ea69", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "mirror-private", codepointHex: "ea75", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "mirror-public", codepointHex: "ea69", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "more", codepointHex: "ea7c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "mortar-board", codepointHex: "eb21", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "move", codepointHex: "eb22", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "multiple-windows", codepointHex: "eb23", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "music", codepointHex: "ec1b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "mute", codepointHex: "eb24", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "new-collection", codepointHex: "ec58", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "new-file", codepointHex: "ea7f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "new-folder", codepointHex: "ea80", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "new-session", codepointHex: "ec84", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "newline", codepointHex: "ebea", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "no-newline", codepointHex: "eb25", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "note", codepointHex: "eb26", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "notebook", codepointHex: "ebaf", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "notebook-template", codepointHex: "ebbf", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "octoface", codepointHex: "eb27", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "open-in-product", codepointHex: "ec65", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "open-in-window", codepointHex: "ec83", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "open-preview", codepointHex: "eb28", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "openai", codepointHex: "ec81", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "organization", codepointHex: "ea7e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "organization-filled", codepointHex: "ea7e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "organization-outline", codepointHex: "ea7e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "output", codepointHex: "eb9d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "package", codepointHex: "eb29", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "paintcan", codepointHex: "eb2a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "parameter-hints-next", codepointHex: nil, deprecatedAliasOf: "chevron-down"),
        MonaIconDefinition(id: "parameter-hints-previous", codepointHex: nil, deprecatedAliasOf: "chevron-up"),
        MonaIconDefinition(id: "pass", codepointHex: "eba4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "pass-compact", codepointHex: "ec9a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "pass-filled", codepointHex: "ebb3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "pass-filled-compact", codepointHex: "ecb5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "pencil", codepointHex: "ea73", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "percentage", codepointHex: "ec33", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "person", codepointHex: "ea67", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "person-add", codepointHex: "ebcd", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "person-filled", codepointHex: "ea67", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "person-follow", codepointHex: "ea67", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "person-outline", codepointHex: "ea67", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "piano", codepointHex: "ec1a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "pie-chart", codepointHex: "ebe4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "pin", codepointHex: "eb2b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "pinned", codepointHex: "eba0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "pinned-dirty", codepointHex: "ebb2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "play", codepointHex: "eb2c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "play-circle", codepointHex: "eba6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "plug", codepointHex: "eb2d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "plus", codepointHex: "ea60", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "preserve-case", codepointHex: "eb2e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "preview", codepointHex: "eb2f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "primitive-dot", codepointHex: "ea71", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "primitive-square", codepointHex: "ea72", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "project", codepointHex: "eb30", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "project-compact", codepointHex: "ecb6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "pulse", codepointHex: "eb31", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "python", codepointHex: "ec39", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "question", codepointHex: "eb32", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "quick-input-back", codepointHex: "ea9b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "quote", codepointHex: "eb33", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "quotes", codepointHex: "ec60", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "radio-tower", codepointHex: "eb34", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "reactions", codepointHex: "eb35", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "record", codepointHex: "eba7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "record-keys", codepointHex: "ea65", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "record-keys-compact", codepointHex: "ec90", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "record-small", codepointHex: "ebfa", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "redo", codepointHex: "ebb0", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "references", codepointHex: "eb36", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "refresh", codepointHex: "eb37", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "refresh-compact", codepointHex: "ecb7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "regex", codepointHex: "eb38", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "remote", codepointHex: "eb3a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "remote-compact", codepointHex: "ec91", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "remote-explorer", codepointHex: "eb39", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "remove", codepointHex: "eb3b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "remove-close", codepointHex: "ea76", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "remove-small", codepointHex: "ec7c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "rename", codepointHex: "ec61", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repl", codepointHex: "ea85", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "replace", codepointHex: "eb3d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "replace-all", codepointHex: "eb3c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "reply", codepointHex: "ea7d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repo", codepointHex: "ea62", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repo-clone", codepointHex: "eb3e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repo-compact", codepointHex: "ec93", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repo-create", codepointHex: "ea60", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repo-delete", codepointHex: "ea62", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repo-fetch", codepointHex: "ec1d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repo-force-push", codepointHex: "eb3f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repo-forked", codepointHex: "ea63", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repo-forked-compact", codepointHex: "ec92", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repo-pinned", codepointHex: "ec43", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repo-pull", codepointHex: "eb40", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repo-push", codepointHex: "eb41", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repo-selected", codepointHex: "ec69", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "repo-sync", codepointHex: "ea77", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "report", codepointHex: "eb42", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "request-changes", codepointHex: "eb43", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "right-panel-hide", codepointHex: "ecc7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "right-panel-show", codepointHex: "ecc8", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "robot", codepointHex: "ec20", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "rocket", codepointHex: "eb44", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "rocket-compact", codepointHex: "ec9d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "root-folder", codepointHex: "eb46", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "root-folder-opened", codepointHex: "eb45", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "rss", codepointHex: "eb47", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "ruby", codepointHex: "eb48", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "run", codepointHex: "eb2c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "run-above", codepointHex: "ebbd", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "run-all", codepointHex: "eb9e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "run-all-coverage", codepointHex: "ec2d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "run-below", codepointHex: "ebbe", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "run-compact", codepointHex: "ecc4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "run-coverage", codepointHex: "ec2c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "run-errors", codepointHex: "ebde", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "run-with-deps", codepointHex: "ec62", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "save", codepointHex: "eb4b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "save-all", codepointHex: "eb49", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "save-as", codepointHex: "eb4a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "screen-cut", codepointHex: "ec7f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "screen-full", codepointHex: "eb4c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "screen-normal", codepointHex: "eb4d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "scrollbar-button-down", codepointHex: "eb6e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "scrollbar-button-left", codepointHex: "eb6f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "scrollbar-button-right", codepointHex: "eb70", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "scrollbar-button-up", codepointHex: "eb71", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "search", codepointHex: "ea6d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "search-compact", codepointHex: "ecb8", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "search-fuzzy", codepointHex: "ec0d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "search-large", codepointHex: "ec70", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "search-save", codepointHex: "ea6d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "search-sparkle", codepointHex: "ec50", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "search-stop", codepointHex: "eb4e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "selection", codepointHex: "eb85", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "send", codepointHex: "ec0f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "send-to-remote-agent", codepointHex: "ec53", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "server", codepointHex: "eb50", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "server-environment", codepointHex: "eba3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "server-process", codepointHex: "eba2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "session-in-progress", codepointHex: "ec77", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "session-in-progress-compact", codepointHex: "ecb9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "settings", codepointHex: "eb52", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "settings-compact", codepointHex: "ecc2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "settings-gear", codepointHex: "eb51", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "share", codepointHex: "ec25", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "share-window", codepointHex: "ec88", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "shield", codepointHex: "eb53", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "shield-compact", codepointHex: "ec94", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "sign-in", codepointHex: "ea6f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "sign-out", codepointHex: "ea6e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "skip", codepointHex: "ec6a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "smiley", codepointHex: "eb54", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "snake", codepointHex: "ec16", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "sort-percentage", codepointHex: "ec33", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "sort-precedence", codepointHex: "eb55", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "source-control", codepointHex: "ea68", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "sparkle", codepointHex: "ec10", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "sparkle-compact", codepointHex: "ec95", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "sparkle-filled", codepointHex: "ec21", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "split-horizontal", codepointHex: "eb56", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "split-vertical", codepointHex: "eb57", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "squirrel", codepointHex: "eb58", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "star", codepointHex: "ea6a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "star-add", codepointHex: "ea6a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "star-delete", codepointHex: "ea6a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "star-empty", codepointHex: "ea6a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "star-full", codepointHex: "eb59", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "star-half", codepointHex: "eb5a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "stop", codepointHex: "ea87", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "stop-circle", codepointHex: "eba5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "strikethrough", codepointHex: "ec64", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "suggest-more-info", codepointHex: nil, deprecatedAliasOf: "chevron-right"),
        MonaIconDefinition(id: "surround-with", codepointHex: "ec24", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-array", codepointHex: "ea8a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-boolean", codepointHex: "ea8f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-class", codepointHex: "eb5b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-color", codepointHex: "eb5c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-color-compact", codepointHex: "ec96", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-constant", codepointHex: "eb5d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-constructor", codepointHex: "ea8c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-customcolor", codepointHex: "eb5c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-enum", codepointHex: "ea95", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-enum-member", codepointHex: "eb5e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-event", codepointHex: "ea86", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-field", codepointHex: "eb5f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-file", codepointHex: "eb60", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-folder", codepointHex: "ea83", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-function", codepointHex: "ea8c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-interface", codepointHex: "eb61", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-key", codepointHex: "ea93", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-keyword", codepointHex: "eb62", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-method", codepointHex: "ea8c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-method-arrow", codepointHex: "ec41", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-misc", codepointHex: "eb63", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-module", codepointHex: "ea8b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-namespace", codepointHex: "ea8b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-null", codepointHex: "ea8f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-number", codepointHex: "ea90", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-numeric", codepointHex: "ea90", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-object", codepointHex: "ea8b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-operator", codepointHex: "eb64", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-package", codepointHex: "ea8b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-parameter", codepointHex: "ea92", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-property", codepointHex: "eb65", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-reference", codepointHex: "ea94", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-ruler", codepointHex: "ea96", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-snippet", codepointHex: "eb66", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-string", codepointHex: "eb8d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-struct", codepointHex: "ea91", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-structure", codepointHex: "ea91", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-text", codepointHex: "ea93", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-type-parameter", codepointHex: "ea92", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-unit", codepointHex: "ea96", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-value", codepointHex: "ea95", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "symbol-variable", codepointHex: "ea88", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "sync", codepointHex: "ea77", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "sync-compact", codepointHex: "ecba", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "sync-ignored", codepointHex: "eb9f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "table", codepointHex: "ebb7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "tag", codepointHex: "ea66", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "tag-add", codepointHex: "ea66", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "tag-remove", codepointHex: "ea66", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "target", codepointHex: "ebf8", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "tasklist", codepointHex: "eb67", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "telescope", codepointHex: "eb68", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal", codepointHex: "ea85", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal-bash", codepointHex: "ebca", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal-cmd", codepointHex: "ebc4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal-compact", codepointHex: "ecbb", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal-debian", codepointHex: "ebc5", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal-decoration-error", codepointHex: "ebfb", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal-decoration-incomplete", codepointHex: "eabc", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal-decoration-mark", codepointHex: "eb8a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal-decoration-success", codepointHex: "ea71", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal-git-bash", codepointHex: "ec71", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal-linux", codepointHex: "ebc6", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal-powershell", codepointHex: "ebc7", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal-secure", codepointHex: "ec85", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal-tmux", codepointHex: "ebc8", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "terminal-ubuntu", codepointHex: "ebc9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "text-size", codepointHex: "eb69", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "thinking", codepointHex: "ec59", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "three-bars", codepointHex: "eb6a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "thumbsdown", codepointHex: "eb6b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "thumbsdown-filled", codepointHex: "ec13", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "thumbsup", codepointHex: "eb6c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "thumbsup-filled", codepointHex: "ec14", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "toolbar-more", codepointHex: "ea7c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "tools", codepointHex: "eb6d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "trash", codepointHex: "ea81", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "trashcan", codepointHex: "ea81", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "tree-filter-clear", codepointHex: "ea76", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "tree-filter-on-type-off", codepointHex: "eb85", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "tree-filter-on-type-on", codepointHex: "eb83", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "tree-item-expanded", codepointHex: "eab4", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "tree-item-loading", codepointHex: "eb19", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "triangle-down", codepointHex: "eb6e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "triangle-left", codepointHex: "eb6f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "triangle-right", codepointHex: "eb70", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "triangle-up", codepointHex: "eb71", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "twitter", codepointHex: "eb72", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "type-hierarchy", codepointHex: "ebb9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "type-hierarchy-sub", codepointHex: "ebba", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "type-hierarchy-super", codepointHex: "ebbb", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "unarchive", codepointHex: "ec76", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "unfold", codepointHex: "eb73", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "ungroup-by-ref-type", codepointHex: "eb98", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "unlock", codepointHex: "eb74", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "unmute", codepointHex: "eb75", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "unpin", codepointHex: "ec9e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "unverified", codepointHex: "eb76", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "variable", codepointHex: "ea88", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "variable-group", codepointHex: "ebb8", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "verified", codepointHex: "eb77", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "verified-filled", codepointHex: "ebe9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "versions", codepointHex: "eb78", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "vm", codepointHex: "ea7a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "vm-active", codepointHex: "eb79", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "vm-compact", codepointHex: "ecc3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "vm-connect", codepointHex: "eba9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "vm-outline", codepointHex: "eb7a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "vm-pending", codepointHex: "ecbc", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "vm-running", codepointHex: "eb7b", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "vm-small", codepointHex: "ec79", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "voice-mode", codepointHex: "eccb", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "voice-mode-compact", codepointHex: "eccc", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "vr", codepointHex: "ec18", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "vscode", codepointHex: "ec29", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "vscode-insiders", codepointHex: "ec2a", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "vscode-insiders-outline", codepointHex: "ecc9", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "vscode-outline", codepointHex: "ecca", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "wand", codepointHex: "ebcf", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "warning", codepointHex: "ea6c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "warning-compact", codepointHex: "ec99", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "watch", codepointHex: "eb7c", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "whitespace", codepointHex: "eb7d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "whole-word", codepointHex: "eb7e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "widget-close", codepointHex: nil, deprecatedAliasOf: "close"),
        MonaIconDefinition(id: "window", codepointHex: "eb7f", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "window-active", codepointHex: "ec72", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "window-compact", codepointHex: "ec97", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "word-wrap", codepointHex: "eb80", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "workspace-trusted", codepointHex: "ebc1", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "workspace-unknown", codepointHex: "ebc3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "workspace-unspecified", codepointHex: "ebc3", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "workspace-untrusted", codepointHex: "ebc2", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "worktree", codepointHex: "ec7e", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "worktree-compact", codepointHex: "ecbd", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "worktree-small", codepointHex: "ec7d", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "wrench", codepointHex: "eb65", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "wrench-subaction", codepointHex: "eb65", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "x", codepointHex: "ea76", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "zap", codepointHex: "ea86", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "zoom-in", codepointHex: "eb81", deprecatedAliasOf: nil),
        MonaIconDefinition(id: "zoom-out", codepointHex: "eb82", deprecatedAliasOf: nil),
    ]

    private static let idIndex: [String: Int] = {
        var idx: [String: Int] = [:]
        for (i, ic) in icons.enumerated() { idx[ic.id] = i }
        return idx
    }()

    /// Looks up an icon definition by id.
    public static func definition(for id: String) -> MonaIconDefinition? {
        guard let i = idIndex[id] else { return nil }
        return icons[i]
    }

    /// All 776 builtin icon ids in source-ordinal order.
    public static var ids: [String] { icons.map { $0.id } }

    /// Resolves `id` to its Codicon codepoint hex string, following deprecated
    /// alias chains. Returns `nil` if the id is unknown.
    public static func codepointHex(for id: String) -> String? {
        var seen: Set<String> = []
        var cur = id
        while let def = definition(for: cur), !seen.contains(cur) {
            seen.insert(cur)
            if let cp = def.codepointHex { return cp }
            if let target = def.deprecatedAliasOf { cur = target; continue }
            return nil
        }
        return nil
    }

    /// Resolves `id` to its Codicon `Character` (the Unicode scalar at the
    /// codepoint's hex value), following alias chains.
    public static func character(for id: String) -> Character? {
        guard let hex = codepointHex(for: id),
              let scalar = UInt32(hex, radix: 16),
              let unicode = UnicodeScalar(scalar) else { return nil }
        return Character(unicode)
    }

    /// The 34 deprecated alias icons (ids that reference another icon id).
    public static var aliases: [MonaIconDefinition] {
        icons.filter { $0.isAlias }
    }
}

